#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys

if sys.version_info[0]<3:       # require python3
 raise Exception("Python3 required! Current (wrong) version: '%s'" % sys.version_info)

sys.path.insert(0, '/var/lib/openshift/589b8f240c1e66aa7c00006e/app-root/repo/')
from server.routes import app as application
